alter table bulletin.attachments add constraint attachments_pkey primary key (id);
alter table bulletin.docs add constraint docs_pkey primary key (id);
alter table bulletin.docs add constraint fk_4qpvhssidoo7hgr9yfood7cwp foreign key (file_id) references bulletin.attachments (id);
alter table bulletin.docs add constraint fk_60rugs17b4if2a0ewkk30088t foreign key (app_id) references cfg.apps (id);
alter table bulletin.docs add constraint fk_iid5l5vv6vmowbdrdu8ltikqk foreign key (upload_by_id) references usr.users (id);
alter table bulletin.docs_user_categories add constraint docs_user_categories_pkey primary key (doc_id,user_category_id);
alter table bulletin.docs_user_categories add constraint fk_ck98wqocenaef81draj19wc9n foreign key (user_category_id) references usr.user_categories (id);
alter table bulletin.docs_user_categories add constraint fk_dns25eb6sy76v277skxxmpcw4 foreign key (doc_id) references bulletin.docs (id);
alter table bulletin.news add constraint news_pkey primary key (id);
alter table bulletin.notices add constraint fk_al9ivcee1cr0a5gkxsxce3rbv foreign key (auditor_id) references usr.users (id);
alter table bulletin.notices add constraint fk_av5607wj4iactc7m2ew0bchah foreign key (operator_id) references usr.users (id);
alter table bulletin.notices add constraint fk_mxlaetoi5frsytq7fjhgat2lc foreign key (app_id) references cfg.apps (id);
alter table bulletin.notices add constraint notices_pkey primary key (id);
alter table bulletin.notices_docs add constraint fk_ea713bax2e8obs9hwjvsvi13g foreign key (doc_id) references bulletin.docs (id);
alter table bulletin.notices_docs add constraint fk_savteekqtgnumi8p2kyh77h09 foreign key (notice_id) references bulletin.notices (id);
alter table bulletin.notices_docs add constraint notices_docs_pkey primary key (notice_id,doc_id);
alter table bulletin.notices_user_categories add constraint fk_g8cnlwsxpfi1xpedsoddjqgya foreign key (user_category_id) references usr.user_categories (id);
alter table bulletin.notices_user_categories add constraint fk_ptcor7fg6nrrvdfavbjqvgdfp foreign key (notice_id) references bulletin.notices (id);
alter table bulletin.notices_user_categories add constraint notices_user_categories_pkey primary key (notice_id,user_category_id);
alter table bulletin.sensitive_words add constraint sensitive_words_pkey primary key (id);
alter table cfg.app_types add constraint app_types_pkey primary key (id);
alter table cfg.apps add constraint apps_pkey primary key (id);
alter table cfg.apps add constraint fk_geo6c41jugjgf7h5tv3yr2bnh foreign key (domain_id) references cfg.domains (id);
alter table cfg.apps add constraint fk_qtajfheyo7x55emd3ncn9x381 foreign key (app_type_id) references cfg.app_types (id);
alter table cfg.credentials add constraint credentials_pkey primary key (id);
alter table cfg.data_sources add constraint data_sources_pkey primary key (id);
alter table cfg.data_sources add constraint fk_11csy9i36qa7xbd0dyhbpf41g foreign key (db_id) references cfg.dbs (id);
alter table cfg.data_sources add constraint fk_cq3geb9r9atwmq6ngtjhutls6 foreign key (credential_id) references cfg.credentials (id);
alter table cfg.data_sources add constraint fk_oesr23l6pnil7g8wf7vkmk6py foreign key (app_id) references cfg.apps (id);
alter table cfg.dbs add constraint dbs_pkey primary key (id);
alter table cfg.dbs_properties add constraint dbs_properties_pkey primary key (db_id,value,name);
alter table cfg.dbs_properties add constraint fk_n3j3tf9w1smqshbhqtckhcu7x foreign key (db_id) references cfg.dbs (id);
alter table cfg.domains add constraint domains_pkey primary key (id);
alter table cfg.domains add constraint fk_n5wxm9d054w67xbjungr1ufdl foreign key (parent_id) references cfg.domains (id);
alter table cfg.orgs add constraint orgs_pkey primary key (id);
alter table se.app_permissions add constraint app_permissions_pkey primary key (id);
alter table se.app_permissions add constraint fk_519oiykea6451ts2vmmetx9hv foreign key (app_id) references cfg.apps (id);
alter table se.app_permissions add constraint fk_lnm7svh5k8hc3drai0ym3m289 foreign key (resource_id) references se.func_resources (id);
alter table se.data_permissions add constraint data_permissions_pkey primary key (id);
alter table se.data_permissions add constraint fk_7m3urbe7j3v4yvrawll4bhaaj foreign key (func_resource_id) references se.func_resources (id);
alter table se.data_permissions add constraint fk_b1c2me26jyv0m0rv4ebsw1xel foreign key (app_id) references cfg.apps (id);
alter table se.data_permissions add constraint fk_q9n4kf29p5wuj7pja83pdoak7 foreign key (resource_id) references se.data_resources (id);
alter table se.data_permissions add constraint fk_toawthk1vaaykhwswsj4sv8ky foreign key (domain_id) references cfg.domains (id);
alter table se.data_permissions add constraint fk_vf8chu885v91mxnost0x8ley foreign key (role_id) references usr.roles (id);
alter table se.data_resources add constraint data_resources_pkey primary key (id);
alter table se.data_resources add constraint fk_ian2ofbtu8g0cig65i51aaigc foreign key (domain_id) references cfg.domains (id);
alter table se.func_permissions add constraint fk_hi3rfwupdve6v17pr2i2mc1q foreign key (resource_id) references se.func_resources (id);
alter table se.func_permissions add constraint fk_kx96j23wqp4uyc63swesg8hss foreign key (role_id) references usr.roles (id);
alter table se.func_permissions add constraint func_permissions_pkey primary key (id);
alter table se.func_resources add constraint fk_njp90obvhc5bv5fvjt2xpb9yd foreign key (app_id) references cfg.apps (id);
alter table se.func_resources add constraint func_resources_pkey primary key (id);
alter table se.menus add constraint fk_cctt24h6nix02cxipt9rbqtnc foreign key (parent_id) references se.menus (id);
alter table se.menus add constraint fk_fjno8g4lqu3b3k0d5flbb187s foreign key (app_id) references cfg.apps (id);
alter table se.menus add constraint fk_o56nmwkbc1xmimpr6obqoircx foreign key (entry_id) references se.func_resources (id);
alter table se.menus add constraint menus_pkey primary key (id);
alter table se.menus_resources add constraint fk_85c54bayea1rq13muto8ut7jy foreign key (menu_id) references se.menus (id);
alter table se.menus_resources add constraint fk_ocur23bmgil049dkq6fyksnga foreign key (func_resource_id) references se.func_resources (id);
alter table se.menus_resources add constraint menus_resources_pkey primary key (menu_id,func_resource_id);
alter table session.session_configs add constraint fk_9clhlrwfu3jvj1inq5phu458y foreign key (category_id) references usr.user_categories (id);
alter table session.session_configs add constraint session_configs_pkey primary key (id);
alter table session.session_events add constraint session_events_pkey primary key (id);
alter table usr.avatars add constraint avatars_pkey primary key (id);
alter table usr.avatars add constraint fk_dh0goytewcg1geffkf1clp4kh foreign key (user_id) references usr.users (id);
alter table usr.dimensions add constraint dimensions_pkey primary key (id);
alter table usr.dimensions_domains add constraint dimensions_domains_pkey primary key (dimension_id,domain_id);
alter table usr.dimensions_domains add constraint fk_i7dg91xcy5trxebfmdaulol68 foreign key (domain_id) references cfg.domains (id);
alter table usr.dimensions_domains add constraint fk_jh4rlsrqy1xqr22wk4q8u39c1 foreign key (dimension_id) references usr.dimensions (id);
alter table usr.group_members add constraint fk_kv9vlrye4rmhqjq4qohy2n5a6 foreign key (group_id) references usr.groups (id);
alter table usr.group_members add constraint fk_nr9qg33qt2ovmv29g4vc3gtdx foreign key (user_id) references usr.users (id);
alter table usr.group_members add constraint group_members_pkey primary key (id);
alter table usr.groups add constraint fk_fvqfb4l9r8hbfhfm515o77esh foreign key (parent_id) references usr.groups (id);
alter table usr.groups add constraint fk_jq37pdrj0mtih03a22mc7noun foreign key (creator_id) references usr.users (id);
alter table usr.groups add constraint groups_pkey primary key (id);
alter table usr.groups_properties add constraint fk_ljmcu3fnj5tljuhw0tdfiu6q4 foreign key (group_id) references usr.groups (id);
alter table usr.groups_properties add constraint groups_properties_pkey primary key (group_id,value,dimension_id);
alter table usr.messages add constraint fk_4ui4nnwntodh6wjvck53dbk9m foreign key (sender_id) references usr.users (id);
alter table usr.messages add constraint fk_hdkwfnspwb3s60j27vpg0rpg6 foreign key (recipient_id) references usr.users (id);
alter table usr.messages add constraint messages_pkey primary key (id);
alter table usr.notifications add constraint fk_qqnsjxlwleyjbxlmm213jaj3f foreign key (recipient_id) references usr.users (id);
alter table usr.notifications add constraint notifications_pkey primary key (id);
alter table usr.role_members add constraint fk_82rdtgk493wmbawb8m3ryrnf2 foreign key (user_id) references usr.users (id);
alter table usr.role_members add constraint fk_lgrk3163r7ti5ctytr1gf48t9 foreign key (role_id) references usr.roles (id);
alter table usr.role_members add constraint role_members_pkey primary key (id);
alter table usr.roles add constraint fk_9uu5b5x4s3hkh76v2t8sgne14 foreign key (creator_id) references usr.users (id);
alter table usr.roles add constraint fk_c8p0cleevyq7r83sa85bn13gm foreign key (parent_id) references usr.roles (id);
alter table usr.roles add constraint roles_pkey primary key (id);
alter table usr.roles_properties add constraint fk_3e3prv62njb0fnipmixpgwupi foreign key (role_id) references usr.roles (id);
alter table usr.roles_properties add constraint roles_properties_pkey primary key (role_id,value,dimension_id);
alter table usr.roots add constraint fk_c6pi0pn5s4fm2mqvwkg8m3qum foreign key (app_id) references cfg.apps (id);
alter table usr.roots add constraint fk_ndc40powte3st4r695eaowtda foreign key (user_id) references usr.users (id);
alter table usr.roots add constraint roots_pkey primary key (id);
alter table usr.todoes add constraint fk_8geny1gyg1nhtelam10fyaxps foreign key (user_id) references usr.users (id);
alter table usr.todoes add constraint fk_n1a51poh6bhsg33dbjnookpas foreign key (domain_id) references cfg.domains (id);
alter table usr.todoes add constraint todoes_pkey primary key (id);
alter table usr.user_categories add constraint user_categories_pkey primary key (id);
alter table usr.user_profiles add constraint fk_129i05sxtrwpag2cd083gi8tu foreign key (domain_id) references cfg.domains (id);
alter table usr.user_profiles add constraint fk_jcad5nfve11khsnpwj1mv8frj foreign key (user_id) references usr.users (id);
alter table usr.user_profiles add constraint user_profiles_pkey primary key (id);
alter table usr.user_profiles_properties add constraint fk_ratfeo83em7bds0jslge8p0ay foreign key (user_profile_id) references usr.user_profiles (id);
alter table usr.user_profiles_properties add constraint user_profiles_properties_pkey primary key (user_profile_id,value,dimension_id);
alter table usr.users add constraint fk_6a5j932mtf9sqiiythm0ey6a2 foreign key (category_id) references usr.user_categories (id);
alter table usr.users add constraint users_pkey primary key (id);
alter table usr.users_properties add constraint fk_8mpw5rvqa6bd98ft8wkcty5aj foreign key (user_id) references usr.users (id);
alter table usr.users_properties add constraint users_properties_pkey primary key (user_id,value,dimension_id);
